### ISSUE TITLE
Align all columns horizontally beside each other + styles

### ISSUE THREAD

**Issue by yharaskrik** [yharaskrik/mtg-visual-deckbuilder#1]
Need to style the columns and label the top as CMC value starting at 0

**Comment by rileyG** [comment]
Obviously this is a first pass, but I think columns should be a bit more customizable. I personally don't build based on CMC, and I'm sure others might want to put sorceries in their own column, etc.

**Comment by yharaskrik** [comment]
Agreed. I think they should be able to choose what the columns are and you can sort by whatever.

**Comment by yharaskrik** [comment]
@rileyG what other ways should we support columns?

Card type, color, what else?

**Comment by rileyG** [comment]
I would also say include freeform. Not sure about what to do when adding new cards to that, though; maybe just put them in either the first or last column.

**Comment by yharaskrik** [comment]
Maybe free form adds an additional "staging" column and removes sort button?

**Comment by rileyG** [comment]
That could work. Maybe called it "Maybe-board" instead of staging. Also on that note, there should be a "Sideboard" column.

**Comment by yharaskrik** [comment]
Ya I was just using staging as a word for staging area. Definitely maybe board. 

And yes sideboard column for sure.

**Comment by rileyG** [comment]
maybe in freeform mode, selecting a card from the `ng-select` dropdown opens a dropout with each of the column names, and you select which column it goes to

**Comment by yharaskrik** [comment]
Closing in favour of #5
