### ISSUE TITLE
Implement other sorting methods

### ISSUE THREAD

**Issue by yharaskrik** [yharaskrik/mtg-visual-deckbuilder#14]
CMC
Type
Freeform

@rileyG if a count it multiple types where should it be put? Obviously the user and drag and drop it but if they click the sort button where would it be put? First column it matches? Or make a new column? Allow the user to choose the columns by type? So have a column for each base type but then they can enable artifact enchantment alongside an enchantment column and artifact column?

**Comment by rileyG** [comment]
I've been thinking about it, and what if it was just free-form, and people could rename the columns to their liking. Obviously sorting would be nice, but I think having it only be free-form is a cleaner solution. We could always "guess" column names based on the inserted cards, if they haven't entered a custom header yet

**Comment by yharaskrik** [comment]
Ya I started implementating free form. Not sure "type" works. Freeform supports column names and such. There's another issue for it.

**Comment by huguenot412** [comment]
I think there should definitely be a freeform option with customizable columns but I also like the idea for having out of the box sorting by things like mana cost and card color. 

In the playmat area to you want everything to stay confined in the available space or allow for horizontal scrolling like the way Trello boards work. I'm thinking horizontal scroll is the way to go.

**Comment by yharaskrik** [comment]
I already started working on freeform, you will be able to choose between cmc and freeform, the former has a sort button.

I would think horizontal scrolling would be better.

**Comment by yharaskrik** [comment]
Closing in favor of #15
