### ISSUE TITLE
UI mockups and ideas

### ISSUE THREAD

**Issue by yharaskrik** [yharaskrik/mtg-visual-deckbuilder#17]
What do we think the structure of the UI should be? Where should the different elements live? I'm not designer, anyone have ideas?

@huguenot412
@rileyG

**Comment by rileyG** [comment]
![basic_brewprints_layout](https://user-images.githubusercontent.com/11969126/120085416-c485f580-c08c-11eb-9ff5-4de5aebeb38f.png)
![basic_brewprints_layout_with_sidebar](https://user-images.githubusercontent.com/11969126/120085421-c8b21300-c08c-11eb-9ec8-a26d27ad757d.png)
Maybe something a little like this? Obviously colours would change, and this is just a bunch of blocks, but it would look better, but laid out like this. Maybe have a setting for which side of the playmat you want the deck info on

**Comment by yharaskrik** [comment]
@projektgopher and @huguenot412 what do you think of Riley's mockups? Chris I know you said your UX designer might be interested in helping as well (mostly putting that here so the others are aware)

**Comment by huguenot412** [comment]
I think this is a good layout. Will there be more going on in the playmat area other than displaying the cards?

**Comment by yharaskrik** [comment]
I don't believe there would be, would just be an area to move cards around in.

**Comment by huguenot412** [comment]
You may have already planned this but I think it would be good to be able to click on a card and have it enlarged. Also, not sure what the API allows, but if we could highlight keyword like "kicker" or "trample" and then have tooltips to give a definition of those terms.

**Comment by yharaskrik** [comment]
I had it zoom on hover before but then riley did some styling and it got removed. We can add it back in, not sure click works because you click to drag? 

The API wouldn't really give us that but we could have a tooltip that shows definitions based on the keywords the card has (which the API does give us)

**Comment by huguenot412** [comment]
Zoom on hover could get annoying unless it just a minor scale increase for user feedback. Maybe just a clickable icon that appears on hover. Most of the card surface could be click to drag but a little icon could let you zoom. There might be a few other actions that could be good to add to an icon bar such as delete or add/remove copies

**Comment by huguenot412** [comment]
Would also be cool to have a social element where you could view friends' decks, copy them, comment on them, etc.

**Comment by yharaskrik** [comment]
Let's split these ideas up into different issues so they can be worked on in parallel. I like em all.

**Comment by huguenot412** [comment]
Sounds good. I just fired up master locally for the first time. I'm going to create a branch an set up the layout.

**Comment by yharaskrik** [comment]
Sweet sounds good! Looking forward to it. Ill triage some of these issues later and clean up the tasks to do.
