### ISSUE TITLE
Style the search with a small image of the card to the left or right

### ISSUE THREAD

**Issue by yharaskrik** [yharaskrik/mtg-visual-deckbuilder#4]
take a look at how tappedout shows you cards when you are adding them to a deck in their builder.

Also maybe mana cost to the left of the name with svgs of each mana symbol?

**Comment by rileyG** [comment]
the archive containing the manamojis from Scryfall seems to be down right now, so I'm just going to put the raw casting cost string from the JSON underneath the card name for now. That should be a good enough reminder to change it later.

**Comment by yharaskrik** [comment]
didnt even know they had an archive for that. Cool.

**Comment by rileyG** [comment]
<img width="1436" alt="Screen Shot 2021-05-31 at 5 50 27 PM" src="https://user-images.githubusercontent.com/11969126/120252221-c2f93080-c238-11eb-85a0-2d37bb82517a.png">
Having the card images pop up with the search in the sidebar is a little too size prohibitive, so the options are not have the images in the search, or maybe move the search bar above the playmat like so. What are everybody else's thoughts?

**Comment by yharaskrik** [comment]
Hmm, I do like having the images there (like how tappedout does it), but it might make more sense to just have the names and not even do images or mana symbols?

**Comment by yharaskrik** [comment]
Ya not a lot of room hey, well if we can get the mana symbols working that would be really cool.
